### ISSUE TITLE
Style file should be reopened after packaged installed.

### ISSUE THREAD

**Issue by zeakd** [adarrra/css-color-name#2]
Thanks for this nice tool! This is what I really needed.
There is small problem. It was not working right after package installed if the style file is opened. All style file should be reopened. I'm not sure it is a natural atom package behavior.., but I just want to tell you about it :D

**Comment by adarrra** [comment]
Hi!
I'm glad that package is useful for you.)
I will investigate this

**Comment by adarrra** [comment]
I hadn't find direct information but see that others (even popular) packages work the same way. So I close this issue
